data:
  sources: ["csv", "shioaji"]
  csv_pattern: "./data/{symbol}.csv"
run:
  symbols: ["0050"]
  start: "2018-01-01"
  end: "2025-01-01"
  nl_grid:
    - [10, 20]
  param_grid:
    - { n: 10, l: 20, slippage: 0.2 }
    - { n: 20, l: 40, slippage: 0.3, multiplier: 1.0, fee_rate_per_side: 0.0005 }
  strategies: ["S1", "S2", "S3", "S4"]
  slippage: 0.2
costs:
  multiplier: 1.0
  fee_fixed_per_side: 0.0
  fee_rate_per_side: 0.0
output:
  dir: "./outputs"
  embed_images: true
risk:
  trading_days_per_year: 252
  risk_free_rate: 0.0
